name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta todos los días a medianoche
  workflow_dispatch: # Permite ejecutarlo a mano si quieres

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update bot file
        run: |
          echo "Last activity: $(date)" > bot.txt

      - name: Commit changes
        run: |
          git config --local user.email "angelgabrielnieto@outlook.com"
          git config --local user.name "NopAngel"
          git add bot.txt
          git commit -m "chore: daily system sync xd"
          git push
